defaults:
    - default

name: SemiCPFSI
latent_dim: ${latent_dim}
alpha: ${alpha}
beta: ${beta}
gamma: ${gamma}

target:
    _target_: src.models.cpfsi.SemiCPFSI

encoder:
    hidden_dims: ${datamodule.encoder.hidden_dims}
    output_dim: ${..latent_dim}


decoder:
    input_dim: ${..latent_dim}
    hidden_dims: ${datamodule.decoder.hidden_dims}


predictor:
    input_shape: ${..latent_dim}
    hidden_dims: ${datamodule.predictor.hidden_dims}
