defaults:
    - default

name: SemiIBSI
latent_dim: ${latent_dim}
alpha: ${alpha}
beta: ${beta}
gamma: ${beta}

target:
    _target_: src.models.ibsi.SemiIBSI


encoder:
    hidden_dims: ${datamodule.encoder.hidden_dims}
    output_dim: ${..latent_dim}


decoder:
    input_dim: ${..latent_dim}
    hidden_dims: ${datamodule.decoder.hidden_dims}

predictor:
    input_shape: ${..latent_dim}
    hidden_dims: ${datamodule.predictor.hidden_dims}
