defaults:
    - default

name: VFAE  # Unsupervised
latent_dim: ${latent_dim}
gamma: ${gamma}

target:
    _target_: src.models.vfae.VFAE

encoder:
    hidden_dims: ${datamodule.encoder.hidden_dims}
    output_dim: ${..latent_dim}

decoder:
    input_dim: ${..latent_dim}
    hidden_dims: ${datamodule.decoder.hidden_dims}
